name: mycicdlab
on:
	push:
		branches:
			- main
	pull_request:
		branches:
			- main
jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout Code Repository
				uses: actions/checkout@v2
			- name: Setup Node.js
				uses: actions/setup-node@v2
				with:
					node-version: '20’
			- name: Install Dependencies
				run: npm install
			- name: Build Application
				run: npm run build
			- name: Run Tests
				run: npm test

